config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :users, only: %i[index] do
    member do
      get :following, :followers
    end
  end
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'posts#index'
  resources :posts, only: %i[show new create index destroy]
  resources :relationships, only: [:create, :destroy]
  get '/:nickname', to: 'users#show', as: 'user_show'
  resources :likes, only: [:create, :destroy]
  resources :posts, only: %i[new create index] do
    resources :comments, only: %i[create]
  end
  resources :comments , only: %i[create] do
    resources :comments, only: %i[create]
  end
  resources :posts, only: %i[new create index] do
    resources :likes, only: [:create], on: :member
    delete '/likes', to: 'likes#destroy', on: :member, as: :post_likes_destroy
  end
  resources :comments, only: %i[create] do
    resources :likes, only: [:create], on: :member
    delete '/likes', to: 'likes#destroy', on: :member, as: :comment_likes_destroy
  end

  namespace :api, defaults: { format: "json" } do
    mount_devise_token_auth_for 'User', at: 'auth'
    namespace :v1 do
      resources :posts, only: %i[show update]
      resources :users, only: [:index] do
        resources :posts, only: %i[index create]
      end
    end
  end
end

app/views/partials/_btn-follow.html.haml
%button.btn.btn-primary.btn-follow{ type: 'button', data: { user_id: user.id, follows: following, is_current_user: is_current_user, is_side_user: is_side_user, in_following: in_following, in_followers: in_followers, target: "#row-user-#{user.id}", current_id: current_user.id }, remote: true }
  = current_user.following?(user) ? 'Unfollow' : 'Follow'

app/views/partials/_filter_posts.html.haml
.filter-container
  Author:
  = text_field_tag :author_filter, params[:author_filter], class: 'input form-control filter-input author-filter', placeholder: 'Author'

  Post title:
  = text_field_tag :title_filter, params[:title_filter], class: 'input form-control filter-input title-filter', placeholder: 'Title'

  Post body:
  = text_field_tag :body_filter, params[:body_filter], class: 'input form-control filter-input body-filter', placeholder: 'Body'

  .form-check
    %input#last_day.form-check-input{ name: 'date_filter', type: 'radio', value: 'Last day' }
      Last day
  .form-check
    %input#last_week.form-check-input{ name: 'date_filter', type: 'radio', value: 'Last week' }
      Last week
  .form-check
    %input#last_month.form-check-input{ name: 'date_filter', type: 'radio', value: 'Last month' }
      Last month

  = button_tag 'Apply filters', class: 'btn btn-primary btn-apply', id: 'apply-filters-button'
  = button_tag 'Clear filters', class: 'btn btn-secondary btn-clear', id: 'clear-filters-button'

app/views/partials/_header.html.haml
.header-content
  = link_to root_path do
    = image_tag 'Neocoast_Logos_RGB-06.svg', size: '83x40'
  - if user_signed_in?
    = link_to 'Users', users_path, class: 'button btn btn-primary btn-users'
    = form_tag users_path, class: 'user-search', method: :get do
      = text_field_tag :search, params[:search], id: 'search-input', class: 'input form-control search-input', placeholder: 'Search user'
      = button_tag 'Search', class: 'btn btn-primary search-button', id: 'search-button'

app/views/partials/_modal_delete.html.haml
/ Button trigger modal
%button.btn.btn-primary.btn-delete{ "data-post-id" => post_id, "data-target" => "#modalId", "data-toggle" => "modal", "type" => "button" }
  Delete

/ Modal
.modal
  .modal-dialog.modal-dialog-centered{ role: "document" }
    .modal-content
      .modal-body
        Are you sure you want to delete this post?
      .modal-footer
        %button.btn.btn-secondary.close-modal{ "data-dismiss" => "modal", type: "button" } Close
        %button.btn.btn-primary.btn-delete-post{ type: "button", "data-post-id" => post_id, "data-in-index" => in_index } Delete

app/views/partials/_side-bar.html.haml
= link_to user_show_path(user.nickname) do
  .side-bar.d-flex.flex-column.align-items-center
    = image_tag user.avatar, class: 'rounded-circle user-img'
    .data
      = user.nickname
      = link_to 'New post', 'posts/new', class: 'btn btn-primary btn-newPost'
      = button_to 'Sign out', destroy_user_session_path, method: :delete, class: 'btn-logOut'

app/views/partials/_sort_posts.html.haml
.dropdown
  %button.btn.btn-primary.dropdown-toggle.btn-dropdown{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", type: "button"}
    Sort posts
  .dropdown-menu{"aria-labelledby" => "dropdownMenuButton"}
    %a.dropdown-item{ href: "#", data: { sort_by: 'Publishing date' } } Publishing date
    %a.dropdown-item{ href: "#", data: { sort_by: 'Number of likes' }  } Number of likes
    %a.dropdown-item{ href: "#", data: { sort_by: 'Trending' }  } Trending