config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :users, only: %i[index] do
    member do
      get :following, :followers
    end
  end
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'posts#index'
  resources :posts, only: %i[show new create index destroy]
  resources :relationships, only: [:create, :destroy]
  get '/:nickname', to: 'users#show', as: 'user_show'
  resources :likes, only: [:create, :destroy]
  resources :posts, only: %i[new create index] do
    resources :comments, only: %i[create]
  end
  resources :comments , only: %i[create] do
    resources :comments, only: %i[create]
  end
  resources :posts, only: %i[new create index] do
    resources :likes, only: [:create], on: :member
    delete '/likes', to: 'likes#destroy', on: :member, as: :post_likes_destroy
  end
  resources :comments, only: %i[create] do
    resources :likes, only: [:create], on: :member
    delete '/likes', to: 'likes#destroy', on: :member, as: :comment_likes_destroy
  end

  namespace :api, defaults: { format: "json" } do
    mount_devise_token_auth_for 'User', at: 'auth'
    namespace :v1 do
      resources :posts, only: %i[show update]
      resources :users, only: [:index] do
        resources :posts, only: %i[index create]
      end
    end
  end
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  validates_presence_of :title, :body

  validate :image_file_type

  before_create :set_published_at

  belongs_to :user

  has_one_attached :image

  scope :by_publishing_date, -> { order(published_at: :desc) }
  scope :by_likes, -> { order(likes_count: :desc) }
  scope :by_trending, lambda {
    select(
      'posts.*, ' \
      '(likes_count / ' \
      '(EXP(EXTRACT(EPOCH FROM (CURRENT_TIMESTAMP - published_at)) / (24 * 60 * 60)) / 4)) AS trending'
    ).order('trending DESC')
  }

  has_many :comments, as: :commentable, dependent: :destroy

  has_many :likes, as: :likeable, dependent: :destroy

  scope :filter_author, lambda { |author_filter|
                          if author_filter.present?
                            joins(:user).where('LOWER(users.nickname) = ?', author_filter.downcase)
                          end
                        }
  scope :filter_title, ->(title_filter) { where(title: title_filter) if title_filter.present? }
  scope :filter_body, ->(body_filter) { where(body: body_filter) if body_filter.present? }
  scope :filter_date, lambda { |date_filter, now = Time.zone.now|
    case date_filter
    when 'Last day'
      where('published_at >= ? ', now - 1.day)
    when 'Last week'
      where('published_at >= ?', now.beginning_of_week)
    when 'Last month'
      where('published_at >= ?', now.beginning_of_month)
    else
      all
    end
  }

  scope :sort_posts, lambda { |sort_by|
    case sort_by
    when 'Trending'
      by_trending
    when 'Number of likes'
      by_likes
    else
      by_publishing_date
    end
  }

  private

  def set_published_at
    self.published_at = Time.now
  end

  def image_file_type
    return unless image.attached? && !image.content_type.in?(%w[image/png image/jpg image/jpeg])

    image.purge # Delete the invalid image
    errors.add(:image, 'must be a .jpg, .jpeg or .png image')
  end
end

app/controllers/api/v1/posts_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class PostsController < Api::V1::BaseController
      before_action :find_user, only: %i[index create]
      before_action :find_post, only: %i[show update]

      def index
        return render json: { message: 'User does not exist' }, status: :bad_request unless @user.present?

        @posts = @user.posts.order(published_at: :desc)
      end

      def show
        render json: { message: 'Post does not exist' }, status: :bad_request unless @post.present?
      end

      def create
        return render json: { message: 'Unauthorized' }, status: :unauthorized unless @user == current_user

        @post = @user.posts.build(post_params)
        @post.save if validate_not_empty_attriutes(@post.title, @post.body)
      end

      def update
        return render json: { message: 'Unauthorized' }, status: :unauthorized unless @post&.user == current_user

        new_post = params[:post]
        return unless validate_not_empty_attriutes(new_post[:title], new_post[:body])

        @post.update(post_params)
        render 'api/v1/posts/create', formats: [:json], locals: { post: @post }
      end

      def validate_not_empty_attriutes(title, body)
        unless title.present? && body.present?
          render json: { message: 'Title and body cannot be blank' }, status: :bad_request
          return false
        end
        true
      end

      def find_user
        @user = User.find_by(id: params[:user_id])
      end

      def find_post
        @post = Post.find_by(id: params[:id])
      end

      def post_params
        params.require(:post).permit(:title, :body)
      end
    end
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :find_post, only: %i[show destroy]
  before_action :followed_posts, :define_posts, only: :index

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show; end

  def index
    attachment_partial = render_to_string(partial: 'posts/post', collection: @posts, locals: { in_index: true.to_s })
    respond_to_index(attachment_partial)
  end

  def destroy
    @post.destroy
  end

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body, :image)
  end

  def respond_to_index(attachment_partial)
    respond_to do |format|
      format.html
      format.json { render json: { attachment_partial: } }
    end
  end

  def followed_posts
    @posts = current_user.followed_posts
  end

  def define_posts
    @posts = @posts
             .filter_author(params[:author_filter])
             .filter_body(params[:body_filter])
             .filter_title(params[:title_filter])
             .filter_date(params[:date_filter])
    @posts = @posts.sort_posts(params[:sort_by])
  end
end

app/views/posts/_comment.html.haml
.row.comment-row
  .col-md-1.user-img-comment
    = link_to user_show_path(comment.user.nickname), class: 'user_link_info' do
      = image_tag comment.user.avatar, class: 'rounded-circle user-img-post m-0'
  .col-md-11
    .comment-info.div.card
      = link_to user_show_path(comment.user.nickname), class: 'user_link_info' do
        = comment.user.nickname
        %br
        = comment.user.email
        |
        = distance_of_time_in_words(comment.created_at, Time.now) + ' ago'
    .comment.card
      = comment.content
  - comment_comment_count = comment.comments.count

= render partial: 'posts/new_comment_row', locals: { parent_id: comment.id }
.interactions.comment
  .like
    - liked = comment.likes.find_by(user_id: current_user.id).present?
    = button_tag 'Like', class: 'btn btn-primary btn-like', data: { liked: liked, likeable_id: comment.id, likeable_type: 'Comment' }
    .likes_count
      = comment.likes.count
  .link-to-comments
    .more-less
      view more
    (
    .comment-count
      = comment_comment_count
    )
.comments-comments
  = render partial: 'posts/comment', collection: comment.comments.order(created_at: :desc)
- if comment.commentable_type == 'Post'
  %hr.comment-hr

app/views/posts/_new_comment_row.html.haml
.new-comment-row
  .col-md-1.user-img-new-comment
    = image_tag current_user.avatar, class: 'rounded-circle user-img-post m-0'
  .col-md-11
    %input.form-control.comment-input.comment_comment{ type: "text", name: "comment", placeholder: "Write a comment...", data: { parent_id: parent_id } }

app/views/posts/_post.html.haml
= render partial: 'posts/post_content',  locals: { post: post, post_links: true, in_index: in_index }

app/views/posts/_post_content.html.haml
.row.g-0
  .col-md-1.col-post-data
    - if post.user.avatar.persisted?
      = link_to user_show_path(post.user.nickname), class: 'user_link_info' do
        = image_tag post.user.avatar, class: 'rounded-circle user-img-post'
  .col-md-11
    .post-info.div.card
      .post-intro
        = link_to user_show_path(post.user.nickname), class: 'user_link_info' do
          = post.user.nickname
          %br
          = post.user.email
          |
          = distance_of_time_in_words(post.published_at, Time.now) + ' ago'
        - if post.user == current_user
          = render partial: 'partials/modal_delete', locals: { post_id: post.id, in_index: in_index }
      - if post_links
        = link_to post_path(post), class: 'post_link' do
          = render partial: 'posts/post_elements', locals: { post: post }
      - else
        = render partial: 'posts/post_elements', locals: { post: post }
  .interactions
    .like
      - liked = post.likes.find_by(user_id: current_user.id).present?
      = button_tag 'Like', class: 'btn btn-primary btn-like', data: { liked: liked, likeable_id: post.id, likeable_type: 'Post' }, remote: true
      .likes_count
        = post.likes.count
    = link_to post_path(post, anchor: 'post_comment'), class: 'btn btn-comment btn-primary' do
      Comment
    .comments_count
      = post.comments.count

app/views/posts/_post_elements.html.haml
.card-body
  %h5.card-title
    = post.title
  %p.card-text.mt-3
    = post.body
    - if post.image.present?
      = image_tag post.image, class: 'post-img mt-2'

app/views/posts/_single_post.html.haml
.row.g-0
  .col-md-1
    = image_tag post.user.avatar, class: 'rounded-circle user-img-post'
  .col-md-11
    .post-info.div.card
      = post.user.nickname
      %br
      = post.user.email
      |
      = distance_of_time_in_words(post.published_at, Time.now)
      .card-body.mt-2
        %h5.card-title
          = post.title
        %p.card-text.mt-3
          = post.body
          - if post.image.present?
            = image_tag post.image, class: 'post-img mt-2'

app/views/posts/index.html.haml
.wrapper
  .side
    = render partial: 'partials/side-bar', locals: { user: current_user }
    = render partial: 'partials/sort_posts'

  .posts-container.filter-index.d-flex.flex-column
    - if @posts.present?
      = render partial: 'post', collection: @posts, locals: { in_index: true.to_s }
    - else
      .no-posts
        No posts found

  = render partial: 'partials/filter_posts'

app/views/posts/new.html.haml
.new-post-container
  %h2 Add a new post
  = form_for @post do |f|
    .field
      = f.label :title, class: 'form-label mt-2'
      = f.text_field :title, autofocus: true, autocomplete: 'title', class: 'form-control mb-2'
      = render 'errors/error_fields', errors: @post.errors[:title]
    .field
      = f.label :body, class: 'form-label mt-2'
      = f.text_area :body, autofocus: true, autocomplete: 'body', rows: 10, class: 'form-control mb-2'
      = render 'errors/error_fields', errors: @post.errors[:body]
    .field
      = f.label :image, class: 'form-label mt-2'
      = f.file_field :image, accept: 'image/jpeg,image/png', autofocus: true, autocomplete: 'image', class: 'form-control mb-2'
      = render 'errors/error_fields', errors: @post.errors[:image]
    .actions-create-post
      = f.submit 'Create', class: 'btn btn-primary mt-2 btn-create-post'

app/views/posts/show.html.haml
.posts-container.post-cont.d-flex.flex-column.mb-4
  .back-btn
    back
  %hr
  = render partial: 'post_content', locals: { post: @post, post_links: false, in_index: false.to_s }

  .comments-container.d-flex.flex-column.align-items-center
    = render partial: 'comment', collection: @post.comments.order(created_at: :desc)

  .new-comment-row-post
    .col-md-1
      = image_tag current_user.avatar, class: 'rounded-circle user-img-post m-0'
    .col-md-11
      %input.form-control.comment-input#post_comment{ type: "text", name: "comment", placeholder: "Write a comment...", data: { parent_id: @post.id } }